import{SettingsManager}from'./SettingsManager.js';import{SaveManager}from'./SaveManager.js';import{PerformanceManager}from'./PerformanceManager.js';import{AudioManager}from'./AudioManager.js';import{InputManager}from'../input/InputManager.js';import{MapManager}from'../map/MapManager.js';import{WeaponManager}from'../weapons/WeaponManager.js';import{PlayerController}from'../player/PlayerController.js';import{BotManager}from'../ai/BotManager.js';import{MatchManager}from'../game/MatchManager.js';import{UIManager}from'../ui/UIManager.js';import{TargetManager}from'../targets/TargetManager.js';import{WEAPONS}from'../weapons/Weapon.js';
export class Game{constructor(T){this.T=T;this.settings=new SettingsManager();this.save=new SaveManager();this.audio=new AudioManager(this.settings);this.input=new InputManager(document.body,this.settings);this.ui=new UIManager(this.settings,this.save);this.scene=new T.Scene();this.camera=new T.PerspectiveCamera(this.settings.get('fov'),innerWidth/innerHeight,.05,220);this.renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.renderer.outputColorSpace=T.SRGBColorSpace;this.settings.applyQuality(this.renderer);this.renderer.domElement.id='game-canvas';document.getElementById('game-root').appendChild(this.renderer.domElement);this.map=new MapManager(T);this.weapons=new WeaponManager(T,this.camera,this.audio,this.settings);this.bots=new BotManager(T,this);this.match=new MatchManager(this,this.ui);this.targets=new TargetManager(T,this);this.player=null;this.score={A:0,B:0};this.playerHitMeshes=[];this.started=false;this.isPaused=false;this.buyPhase=false;this.buyStartedAt=0;this.respawnDelay=2.2;this.lastDeath=0;this.last=performance.now();this.perf=new PerformanceManager(this.renderer,this.settings)}
async boot(){this.camera.position.set(0,1.6,26);this.scene.add(this.camera);this.map.build(this.scene);this.ensurePlayer();this.buildLoadoutUI();this.bindSettings();this.ui.initSettings(this);this.ui.updateSettingsUI();this.ui.profileScreen();this.applyVisualStyle();this.renderer.setSize(innerWidth,innerHeight);await this.wait(120);this.animate()}
wait(ms){return new Promise(r=>setTimeout(r,ms))}
animate(){requestAnimationFrame(()=>this.animate());const now=performance.now(),dt=Math.min(.05,(now-this.last)/1000);this.last=now;this.perf.update(now);this.targets.update(now);if(this.started){this.match.tickBuy(now);if(!this.isPaused&&!this.buyPhase){this.player.update(dt,now);this.bots.update(dt,now);this.match.update(dt);this.save.data.playTime+=dt;if(Math.floor(this.save.data.playTime)%20===0)this.save.save()}}this.updateHUD();this.renderer.render(this.scene,this.camera)}
ensurePlayer(){if(this.player)return;this.player=new PlayerController(this.T,this.camera,this.input,this.map,this.weapons,this.ui,this.settings,this.audio,this);this.createPlayerHitMeshes()}
createPlayerHitMeshes(){const body=new this.T.Mesh(new this.T.BoxGeometry(.72,1.15,.5),new this.T.MeshBasicMaterial({visible:false})),head=new this.T.Mesh(new this.T.SphereGeometry(.25,8,6),new this.T.MeshBasicMaterial({visible:false}));body.userData={kind:'player',part:'body',owner:this.player};head.userData={kind:'player',part:'head',owner:this.player};this.scene.add(body,head);this.playerHitMeshes=[body,head]}
getShootTargets(){this.playerHitMeshes[0].position.set(this.player.position.x,this.player.position.y-.55,this.player.position.z);this.playerHitMeshes[1].position.set(this.player.position.x,this.player.position.y-.15,this.player.position.z);return [...this.playerHitMeshes,...this.bots.flatMap(b=>b.alive?b.group.children:[]),...this.targets.getHitMeshes()]}
randomSpawn(){return this.map.spawnPoints[Math.floor(Math.random()*this.map.spawnPoints.length)].clone()}randomBotPoint(){return this.map.botSpawns[Math.floor(Math.random()*this.map.botSpawns.length)].clone()}respawnPlayer(){if(this.started&&!this.buyPhase)this.player.spawn(this.randomSpawn())}
applyDamage(target,damage,head,source){if(target?.team&&source?.team&&target.team===source.team)return;if(target===this.player)target.takeDamage(damage,head,source);else if(target?.takeDamage)target.takeDamage(damage,head,source)}
killPlayer(source,head=false){if(!this.player.alive)return;this.player.alive=false;this.lastDeath=performance.now();this.save.add('deaths');this.ui.showDeath('Respawning in '+this.respawnDelay.toFixed(1)+'s');this.ui.killfeed(source?.id||'BOT',this.save.data.username,head,true);if(source?.stats){source.stats.kills++;source.stats.score+=head?120:100}}
killBot(bot,source,head=false){if(!bot.alive)return;bot.alive=false;bot.group.visible=false;bot.stats.deaths++;bot.respawnAt=performance.now()+(this.match.mode==='tactical'?999999:1800);if(source===this.player){this.score.A++;this.save.add('kills');if(head)this.save.add('headshots')}else this.score.B++;this.ui.killfeed(source===this.player?this.save.data.username:(source?.id||'BOT'),bot.id,head,source!==this.player);if(source?.stats){source.stats.kills++;source.stats.score+=head?120:100}this.ui.center(head?'HEADSHOT':'TARGET DOWN',650)}
spawnImpact(point){const m=new this.T.Mesh(new this.T.SphereGeometry(.035,6,4),new this.T.MeshBasicMaterial({color:0xd7dfdb}));m.position.copy(point);this.scene.add(m);setTimeout(()=>m.removeFromParent(),260)}
buildBuyMenu(){if(this._buyBuilt)return;this._buyBuilt=true;const grid=document.getElementById('buy-grid'),ids=['service-pistol','heavy-pistol','burst-pistol','compact-smg','fast-smg','suppressed-smg','assault-rifle','heavy-rifle','burst-rifle','pump-shotgun','auto-shotgun','bolt-sniper','semi-sniper','light-machine'];grid.innerHTML='';for(const id of ids){const d=WEAPONS[id],b=document.createElement('button');b.className='buy-item';b.innerHTML='<b>'+d.name+'</b><span>'+d.type.toUpperCase()+' · '+d.damage+' DMG · '+d.mag+' MAG</span><small>$'+d.price+'</small>';b.addEventListener('click',()=>{this.weapons.setLoadout(id,this.weapons.order[1]||'service-pistol');grid.querySelectorAll('.buy-item').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');this.audio.ui()});grid.appendChild(b)}document.getElementById('buy-done').addEventListener('click',()=>{this.buyPhase=false;this.ui.hide('buy-screen');this.ui.showHUD();this.input.requestLock()})}
buildLoadoutUI(){const grid=document.getElementById('loadout-grid'),ids=Object.keys(WEAPONS).filter(id=>id!=='knife');grid.innerHTML='';for(const id of ids){const d=WEAPONS[id],card=document.createElement('div');card.className='loadout-item';card.innerHTML='<b>'+d.name+'</b><small>'+d.type.toUpperCase()+' · '+d.damage+' damage · '+d.mag+' round mag</small><small>'+d.rate+' RPM · '+d.move.toFixed(1)+' move</small><button>SELECT PRIMARY</button>';card.querySelector('button').addEventListener('click',()=>{this.weapons.setLoadout(id,this.weapons.order[1]||'service-pistol');grid.querySelectorAll('.loadout-item').forEach(x=>x.classList.remove('selected'));card.classList.add('selected');this.save.save()});grid.appendChild(card)}}
bindSettings(){const on=(id,event,fn)=>{const el=document.getElementById(id);if(el)el.addEventListener(event,fn)};const range=(id,key)=>on(id,'input',()=>{const el=document.getElementById(id);if(!el)return;this.settings.set(key,Number(el.value));this.afterSettings(key)});const value=(id,key,parse=v=>v)=>on(id,'change',()=>{const el=document.getElementById(id);if(!el)return;this.settings.set(key,parse(el.value));this.afterSettings(key)});range('setting-fov2','fov');range('setting-sens2','sensitivity');range('setting-zoom','zoomSensitivity');range('setting-hudscale','hudScale');range('setting-master','master');range('setting-sfx','sfx');range('setting-music','music');range('setting-voice','voice');range('setting-scale','renderScale');range('setting-classic-scale','classicScale');range('setting-cross-size','crossSize');range('setting-cross-gap','crossGap');range('setting-cross-thick','crossThick');value('setting-name','username',v=>v.trim().slice(0,16)||'PLAYER');value('setting-style','style');value('setting-autopick','autoPickup');value('setting-autoreload','autoReload');value('setting-fpshud','fpsHud');value('setting-damage-mode','damage');value('setting-invert','invertY',v=>v==='on');value('setting-filter','mouseFilter',v=>v==='on');value('setting-raw','rawInput',v=>v==='on');value('setting-menu-sounds','menuSounds');value('setting-quality-audio','audioQuality');value('setting-quality2','quality');value('setting-shadows','shadows');value('setting-effects','effects');value('setting-hw2','hardware',v=>v==='on');value('setting-cross-style','crossStyle');value('setting-bob2','bob',v=>v==='on');value('setting-sway2','sway',v=>v==='on');value('setting-contrast','contrast');value('setting-cross-dot','crossDot',v=>v==='on');value('setting-cross-outline','crossOutline',v=>v==='on');on('setting-cross-color','input',()=>{this.settings.set('crossColor',document.getElementById('setting-cross-color').value);this.afterSettings('crossColor')});on('settings-reset','click',()=>{this.settings.reset();this.applyVisualStyle();this.settings.applyQuality(this.renderer);this.ui.updateSettingsUI()});this.afterSettings('init')}
afterSettings(key){if(key==='fov'||key==='init'){this.camera.fov=this.settings.get('fov');this.camera.updateProjectionMatrix()}if(key==='style'||key==='init')this.applyVisualStyle();if(key==='master'&&this.audio.master)this.audio.master.gain.value=this.settings.get('master')*.22;this.settings.applyQuality(this.renderer);if(this.ui)this.ui.updateSettingsUI()}
applyVisualStyle(){const style=this.settings.get('style')||'modern';document.body.dataset.style=style;document.body.classList.toggle('classic16',style==='classic16');document.documentElement.style.setProperty('--classic-scale',String((this.settings.get('classicScale')||100)/100));document.body.classList.toggle('high-contrast',this.settings.get('contrast')==='high')}
bindUI(){document.querySelectorAll('[data-menu]').forEach(b=>b.addEventListener('click',()=>{this.audio.ui();this.handleMenu(b.dataset.menu)}));document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{this.audio.ui();this.beginMode(b.dataset.mode)}));document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>this.ui.show(b.dataset.back==='menu'?'menu-screen':b.dataset.back)));document.getElementById('resume-button').addEventListener('click',()=>this.resume());document.getElementById('restart-button').addEventListener('click',()=>this.restart());document.getElementById('quit-button').addEventListener('click',()=>this.quit());window.addEventListener('keydown',e=>this.handleKey(e));window.addEventListener('keyup',e=>{if(e.code===this.settings.data.binds.scoreboard)document.getElementById('scoreboard').classList.add('hidden')});this.renderer.domElement.addEventListener('click',()=>{if(this.started&&!this.isPaused&&!this.buyPhase)this.input.requestLock()})}
handleMenu(k){if(k==='practice')return this.beginMode('practice');const map={play:'mode-screen',loadout:'loadout-screen',settings:'settings-screen',profile:'profile-screen'};if(k==='profile')this.ui.profileScreen();if(k==='settings')this.ui.updateSettingsUI();if(map[k])this.ui.show(map[k])}
beginMode(mode){this.ui.show('loading-screen');const fill=document.getElementById('loading-fill');fill.style.width='0%';let n=0;const go=()=>{n+=25;fill.style.width=n+'%';document.getElementById('loading-title').textContent=['LOADOUT','MAP','BOTS','READY'][n/25-1];if(n<100)setTimeout(go,90);else setTimeout(()=>this.start(mode),160)};go()}
start(mode){this.started=true;this.isPaused=false;this.ui.hideScreens();this.match.start(mode);if(!this.buyPhase)this.input.requestLock()}
handleKey(e){if(e.code==='Escape'&&this.started&&!this.buyPhase){if(this.isPaused)this.resume();else this.pause()}if(!this.started)return;const b=this.settings.data.binds;if(e.code===b.primary)this.weapons.switchSlot(0);if(e.code===b.secondary)this.weapons.switchSlot(1);if(e.code===b.knife)this.weapons.switchSlot(2);if(e.code===b.reload&&!this.isPaused)this.weapons.reload(performance.now());if(e.code===b.scoreboard)document.getElementById('scoreboard').classList.remove('hidden')}
pause(){this.isPaused=true;this.input.release();this.ui.show('pause-screen')}resume(){this.isPaused=false;this.ui.hide('pause-screen');if(this.started&&!this.buyPhase)this.input.requestLock()}restart(){const m=this.match.mode;this.quit(false);this.beginMode(m)}quit(show=true){this.started=false;this.isPaused=false;this.buyPhase=false;this.bots.clear();this.targets.setVisible(false);this.ui.hideDeath();this.ui.hideHUD();this.input.release();if(show)this.ui.show('menu-screen')}
updateHUD(){if(!this.player)return;const w=this.weapons.current();this.ui.setAmmo(w.ammo,w.reserve,w.def.name);this.ui.setScore(this.match.teamScore.A,this.match.teamScore.B);const s=this.perf.stats();document.getElementById('ping-value').textContent='18';document.getElementById('ping-box').title='FPS '+s.fps+' · Draw calls '+s.drawCalls+' · Triangles '+s.triangles;this.updateScoreboard()}
updateScoreboard(){const rows=[{name:this.save.data.username,k:this.save.data.kills,d:this.save.data.deaths,score:this.score.A*100,ping:18,me:true},...this.bots.map(b=>({name:b.id,k:b.stats.kills,d:b.stats.deaths,score:b.stats.score,ping:20+Math.floor(Math.random()*30)}))].sort((a,b)=>b.score-a.score);this.ui.setScoreboard(rows)}
}