export class SimpleGLBLoader{
constructor(THREE){this.T=THREE}
async loadAsync(url){const res=await fetch(url,{cache:'no-store'});if(!res.ok)throw new Error('GLB request failed: '+res.status+' '+url);return this.parse(await res.arrayBuffer())}
parse(buffer){
const T=this.T,v=new DataView(buffer);if(v.byteLength<20||v.getUint32(0,true)!==0x46546c67)throw new Error('Invalid GLB file');if(v.getUint32(4,true)!==2)throw new Error('Only glTF 2.0 GLB files are supported');
const length=v.getUint32(8,true);let o=12,json=null,bin=null;while(o+8<=length){const n=v.getUint32(o,true),type=v.getUint32(o+4,true),s=o+8,e=s+n;if(e>v.byteLength)throw new Error('Corrupt GLB chunk');if(type===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,s,n)));else if(type===0x004e4942)bin=buffer.slice(s,e);o=e}
if(!json||!bin)throw new Error('GLB missing JSON/BIN chunk');const accessors=json.accessors||[],views=json.bufferViews||[],meshes=json.meshes||[],nodes=json.nodes||[],materials=json.materials||[];
const sizes={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4},counts={SCALAR:1,VEC2:2,VEC3:3,VEC4:4};
const rv=(t,d,p)=>t===5120?d.getInt8(p):t===5121?d.getUint8(p):t===5122?d.getInt16(p,true):t===5123?d.getUint16(p,true):t===5125?d.getUint32(p,true):d.getFloat32(p,true);
const ns=t=>t===5120?1/127:t===5121?1/255:t===5122?1/32767:t===5123?1/65535:1;
const read=(index,float)=>{const a=accessors[index],bv=a&&views[a.bufferView];if(!a||!bv)throw new Error('Missing accessor '+index);const c=counts[a.type],cs=sizes[a.componentType];if(!c||!cs)throw new Error('Unsupported accessor '+index);const stride=bv.byteStride||c*cs,base=(bv.byteOffset||0)+(a.byteOffset||0),count=a.count;if(!float&&a.componentType===5123&&stride===c*2&&base%2===0)return new Uint16Array(bin,base,count*c);if(!float&&a.componentType===5125&&stride===c*4&&base%4===0)return new Uint32Array(bin,base,count*c);if(!float&&a.componentType===5121&&stride===c)return new Uint8Array(bin,base,count*c);const out=new Float32Array(count*c),d=new DataView(bin);for(let i=0;i<count;i++){const row=base+i*stride;for(let j=0;j<c;j++){let x=rv(a.componentType,d,row+j*cs);if(float&&a.normalized)x*=ns(a.componentType);out[i*c+j]=x}}return out};
const getMat=index=>{const m=materials[index];if(!m)return new T.MeshStandardMaterial({color:0x555c58,metalness:.35,roughness:.72});const p=m.pbrMetallicRoughness||{},f=p.baseColorFactor||[.42,.45,.43,1];return new T.MeshStandardMaterial({color:new T.Color(f[0],f[1],f[2]),metalness:p.metallicFactor??.2,roughness:p.roughnessFactor??.75,transparent:f[3]<.999,opacity:f[3],side:T.DoubleSide})};
const makeMesh=index=>{const def=meshes[index],g=new T.Group();if(!def)return g;for(const p of def.primitives||[]){if((p.mode??4)!==4||p.attributes?.POSITION===undefined)continue;const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(read(p.attributes.POSITION,true),3));if(p.attributes.NORMAL!==undefined)geo.setAttribute('normal',new T.BufferAttribute(read(p.attributes.NORMAL,true),3));if(p.attributes.TEXCOORD_0!==undefined)geo.setAttribute('uv',new T.BufferAttribute(read(p.attributes.TEXCOORD_0,true),2));if(p.indices!==undefined)geo.setIndex(new T.BufferAttribute(read(p.indices,false),1));if(!geo.getAttribute('normal'))geo.computeVertexNormals();const m=new T.Mesh(geo,getMat(p.material));m.castShadow=false;m.receiveShadow=true;g.add(m)}return g};
const makeNode=index=>{const n=nodes[index]||{},g=new T.Group();g.name=n.name||'node_'+index;if(n.matrix){g.matrix.fromArray(n.matrix);g.matrixAutoUpdate=false}else{if(n.translation)g.position.fromArray(n.translation);if(n.rotation)g.quaternion.fromArray(n.rotation);if(n.scale)g.scale.fromArray(n.scale)}if(n.mesh!==undefined)g.add(makeMesh(n.mesh));for(const c of n.children||[])g.add(makeNode(c));return g};
const scene=new T.Group(),def=json.scenes?.[json.scene??0];for(const i of def?.nodes||[])scene.add(makeNode(i));if(!scene.children.length)for(let i=0;i<nodes.length;i++)if(!nodes.some(n=>(n.children||[]).includes(i)))scene.add(makeNode(i));return scene;
}
}