export class UIManager{
constructor(settings,save){this.settings=settings;this.save=save;this.hud=document.getElementById('hud');this.screens={};document.querySelectorAll('.screen').forEach(x=>this.screens[x.id]=x);this.bindingNames={forward:'Move Forward',back:'Move Backward',left:'Strafe Left',right:'Strafe Right',sprint:'Sprint',crouch:'Crouch',jump:'Jump',fire:'Fire',ads:'Aim / ADS',reload:'Reload',primary:'Primary Weapon',secondary:'Secondary Weapon',knife:'Knife',use:'Use',scoreboard:'Scoreboard'}}
show(id){Object.values(this.screens).forEach(s=>s.classList.remove('active'));if(this.screens[id])this.screens[id].classList.add('active')}hide(id){this.screens[id]?.classList.remove('active')}hideScreens(){Object.values(this.screens).forEach(s=>s.classList.remove('active'))}showHUD(){this.hud.classList.remove('hidden')}hideHUD(){this.hud.classList.add('hidden')}
setHealth(v){const n=Math.max(0,Math.round(v));document.getElementById('health-value').textContent=n;document.getElementById('health-fill').style.width=n+'%'}setAmmo(c,r,name){document.getElementById('ammo-current').textContent=c;document.getElementById('ammo-reserve').textContent=r;document.getElementById('weapon-label').textContent=name.toUpperCase()}setScore(a,b){document.getElementById('team-a-score').textContent=a;document.getElementById('team-b-score').textContent=b}
setRound(label,time){document.getElementById('round-label').textContent=label;document.getElementById('round-timer').textContent=this.time(time);const el=document.getElementById('buy-timer');if(el)el.textContent=Math.max(0,Math.ceil(time))}time(sec){sec=Math.max(0,Math.ceil(sec));return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
killfeed(killer,victim,head=false,enemy=false){const f=document.getElementById('kill-feed'),line=document.createElement('div');line.className='kill-line'+(enemy?' enemy':'');line.textContent=killer+'  ›  '+victim+(head?'  HEADSHOT':'');f.prepend(line);while(f.children.length>5)f.lastChild.remove();setTimeout(()=>line.remove(),4500)}
center(text,ms=1300){const e=document.getElementById('center-message');e.textContent=text;clearTimeout(this.timer);this.timer=setTimeout(()=>e.textContent='',ms)}flashDamage(){const e=document.getElementById('damage-indicator');e.classList.add('hit');clearTimeout(this.damageTimer);this.damageTimer=setTimeout(()=>e.classList.remove('hit'),120)}showDeath(text){document.getElementById('death-screen').classList.add('active');document.getElementById('death-message').textContent=text}hideDeath(){document.getElementById('death-screen').classList.remove('active')}
setScoreboard(rows){document.getElementById('scoreboard-rows').innerHTML=rows.map(r=>'<div class="score-row '+(r.me?'me':'')+'"><span>'+r.name+'</span><span>'+r.k+'</span><span>'+r.d+'</span><span>'+r.score+'</span><span>'+r.ping+'</span></div>').join('')}
profileScreen(){const d=this.save.data;document.getElementById('profile-name').textContent=d.username;const s=[['KILLS',d.kills],['DEATHS',d.deaths],['K/D',this.save.kd()],['WINS',d.wins],['LOSSES',d.losses],['WIN %',this.save.winRate()],['HEADSHOTS',d.headshots],['PLAY TIME',Math.floor(d.playTime/60)+'m']];document.getElementById('profile-grid').innerHTML=s.map(v=>'<div class="stat"><b>'+v[1]+'</b><span>'+v[0]+'</span></div>').join('')}
initSettings(game){this.game=game;document.querySelectorAll('.settings-tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.settings-tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.settings-pane').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('[data-pane="'+btn.dataset.tab+'"]')?.classList.add('active')}));this.buildBindings(game.input)}
formatBind(code){if(!code)return'UNBOUND';if(code.startsWith('Mouse'))return code==='Mouse0'?'LMB':code==='Mouse2'?'RMB':code;if(code==='Space')return'SPACE';if(code.startsWith('Shift'))return'SHIFT';if(code.startsWith('Control'))return'CTRL';if(code.startsWith('Alt'))return'ALT';if(code.startsWith('Key'))return code.slice(3).toUpperCase();if(code.startsWith('Digit'))return code.slice(5);if(code==='Tab')return'TAB';return code.toUpperCase()}
buildBindings(input){const host=document.getElementById('bind-list');if(!host)return;host.innerHTML='';for(const[name,label]of Object.entries(this.bindingNames)){const row=document.createElement('div');row.className='bind-row';const text=document.createElement('span');text.textContent=label;const button=document.createElement('button');button.textContent=this.formatBind(this.settings.data.binds[name]);button.addEventListener('click',()=>{document.querySelectorAll('.bind-row button').forEach(x=>x.classList.remove('waiting'));button.classList.add('waiting');button.textContent='PRESS KEY';const handler=e=>{e.preventDefault();input.setBind(name,e.code);button.textContent=this.formatBind(e.code);button.classList.remove('waiting');window.removeEventListener('keydown',handler);this.settings.save()};window.addEventListener('keydown',handler,{once:false})});row.append(text,button);host.appendChild(row)}}
updateSettingsUI(){const s=this.settings.data;const set=(id,v)=>{const e=document.getElementById(id);if(e)e.value=v};const check=(id,v)=>{const e=document.getElementById(id);if(e)e.checked=!!v};set('setting-name',s.username);set('setting-style',s.style);set('setting-autopick',s.autoPickup);set('setting-autoreload',s.autoReload);set('setting-fpshud',s.fpsHud);set('setting-damage-mode',s.damage);set('setting-sens2',s.sensitivity);set('setting-zoom',s.zoomSensitivity);set('setting-invert',s.invertY?'on':'off');set('setting-filter',s.mouseFilter?'on':'off');set('setting-raw',s.rawInput?'on':'off');set('setting-master',s.master);set('setting-sfx',s.sfx);set('setting-music',s.music);set('setting-voice',s.voice);set('setting-menu-sounds',s.menuSounds);set('setting-quality-audio',s.audioQuality);set('setting-fov2',s.fov);set('setting-fps2',s.fps);set('setting-scale',s.renderScale);set('setting-quality2',s.quality);set('setting-shadows',s.shadows);set('setting-effects',s.effects);set('setting-hw2',s.hardware?'on':'off');set('setting-cross-style',s.crossStyle);set('setting-bob2',s.bob?'on':'off');set('setting-sway2',s.sway?'on':'off');set('setting-contrast',s.contrast);set('setting-classic-scale',s.classicScale);set('setting-cross-size',s.crossSize);set('setting-cross-gap',s.crossGap);set('setting-cross-thick',s.crossThick);set('setting-cross-color',s.crossColor);set('setting-cross-dot',s.crossDot?'on':'off');set('setting-cross-outline',s.crossOutline?'on':'off');
[['hudscale-out',s.hudScale],['sens2-out',Number(s.sensitivity).toFixed(4)],['zoom-out',s.zoomSensitivity],['master-out',Math.round(s.master*100)+'%'],['sfx-out',Math.round(s.sfx*100)+'%'],['music-out',Math.round(s.music*100)+'%'],['voice-out',Math.round(s.voice*100)+'%'],['fov2-out',s.fov],['scale-out',s.renderScale+'%'],['classic-scale-out',s.classicScale+'%'],['cross-size-out',s.crossSize],['cross-gap-out',s.crossGap],['cross-thick-out',s.crossThick]].forEach(([id,v])=>{const e=document.getElementById(id);if(e)e.textContent=v});
document.documentElement.style.setProperty('--hud-scale',(s.hudScale/100).toFixed(2));const cp=document.getElementById('crosshair-preview');if(cp){cp.style.setProperty('--cross-color',s.crossColor);cp.querySelectorAll('i, b').forEach(e=>e.style.background=s.crossColor);cp.querySelectorAll('i').forEach(e=>{e.style.height=Math.max(2,s.crossSize)+'px';e.style.width=Math.max(1,s.crossThick)+'px'});if(cp.querySelector('b'))cp.querySelector('b').style.display=s.crossDot?'block':'none'}if(this.game?.applyVisualStyle)this.game.applyVisualStyle();if(this.game?.input)this.buildBindings(this.game.input)}
}